// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iasaqwddyppkhldoghqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlhc2Fxd2RkeXBwa2hsZG9naHFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NjI4NDcsImV4cCI6MjA3NDIzODg0N30.UgoJ_jljT7XLkwo6z-GoPYulm0PemI7D39Va8NM_IKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});